input_type: 'PC'
exp_name: PC
pRNN: False # Wether to use pRNN for spatial input and/or internal reward
PC: True # Wether to use fake place cells for spatial input and/or internal reward
CANN: False # Wether to use CANN for spatial input and/or internal reward
recurrence: 1 # Wether to use RNN for memory (1 = don't use, other number = number of recurrent steps)
with_spatial: True # Wether to include spatial input
with_obs: False # Wether to include visual input (in case of recurrency the one that would bypass RNN)
intrinsic: False
theta: False